//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetableSys_T17
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeptInfo
    {
        public DeptInfo()
        {
            this.DegreeInfoes = new HashSet<DegreeInfo>();
            this.LecturerInfoes = new HashSet<LecturerInfo>();
            this.Module1 = new HashSet<Module1>();
        }
    
        public int deptID { get; set; }
        public string deptCode { get; set; }
        public string deptName { get; set; }
    
        public virtual ICollection<DegreeInfo> DegreeInfoes { get; set; }
        public virtual ICollection<LecturerInfo> LecturerInfoes { get; set; }
        public virtual ICollection<Module1> Module1 { get; set; }
        public virtual User1 User1 { get; set; }
    }
}
