//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetableSys_T17
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimetableDbEntities : DbContext
    {
        public TimetableDbEntities()
            : base("name=TimetableDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Building1> Building1 { get; set; }
        public virtual DbSet<DayInfo> DayInfoes { get; set; }
        public virtual DbSet<DegreeInfo> DegreeInfoes { get; set; }
        public virtual DbSet<DeptInfo> DeptInfoes { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<LecturerInfo> LecturerInfoes { get; set; }
        public virtual DbSet<Module1> Module1 { get; set; }
        public virtual DbSet<Park> Parks { get; set; }
        public virtual DbSet<PeriodInfo> PeriodInfoes { get; set; }
        public virtual DbSet<Request1> Request1 { get; set; }
        public virtual DbSet<Room1> Room1 { get; set; }
        public virtual DbSet<RoomRequest> RoomRequests { get; set; }
        public virtual DbSet<RoundInfo> RoundInfoes { get; set; }
        public virtual DbSet<SessionTypeInfo> SessionTypeInfoes { get; set; }
        public virtual DbSet<StatusInfo> StatusInfoes { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
        public virtual DbSet<Week> Weeks { get; set; }
    }
}
