//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetablingSys_T17
{
    using System;
    using System.Collections.Generic;
    
    public partial class LecturerInfo
    {
        public LecturerInfo()
        {
            this.Module1 = new HashSet<Module1>();
        }
    
        public int lecturerID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Module1> Module1 { get; set; }
    }
}
