//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetablingSys_T17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request1
    {
        public Request1()
        {
            this.Room1 = new HashSet<Room1>();
            this.Facilities = new HashSet<Facility>();
            this.RoomRequests = new HashSet<RoomRequest>();
        }
    
        public int requestID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> moduleID { get; set; }
        public Nullable<int> sessionTypeID { get; set; }
        public Nullable<int> dayID { get; set; }
        public Nullable<int> periodID { get; set; }
        public Nullable<int> sessionLength { get; set; }
        public Nullable<int> semester { get; set; }
        public Nullable<int> round { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<int> adhoc { get; set; }
        public string specialRequirement { get; set; }
        public Nullable<int> statusID { get; set; }
        public Nullable<int> weekID { get; set; }
    
        public virtual DayInfo DayInfo { get; set; }
        public virtual Module1 Module1 { get; set; }
        public virtual PeriodInfo PeriodInfo { get; set; }
        public virtual RoundInfo RoundInfo { get; set; }
        public virtual SessionTypeInfo SessionTypeInfo { get; set; }
        public virtual StatusInfo StatusInfo { get; set; }
        public virtual User1 User1 { get; set; }
        public virtual Week Week { get; set; }
        public virtual ICollection<Room1> Room1 { get; set; }
        public virtual ICollection<Facility> Facilities { get; set; }
        public virtual ICollection<RoomRequest> RoomRequests { get; set; }
    }
}
