//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetablingSys_T17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room1
    {
        public Room1()
        {
            this.RoomRequests = new HashSet<RoomRequest>();
            this.Request1 = new HashSet<Request1>();
            this.Facilities = new HashSet<Facility>();
        }
    
        public int roomID { get; set; }
        public string roomCode { get; set; }
        public Nullable<int> buildingID { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> lab { get; set; }
        public Nullable<int> @private { get; set; }
    
        public virtual Building1 Building1 { get; set; }
        public virtual ICollection<RoomRequest> RoomRequests { get; set; }
        public virtual ICollection<Request1> Request1 { get; set; }
        public virtual ICollection<Facility> Facilities { get; set; }
    }
}
