//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetablingSys_T17
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomRequest
    {
        public RoomRequest()
        {
            this.Request1 = new HashSet<Request1>();
        }
    
        public int roomRequestID { get; set; }
        public Nullable<int> roomID { get; set; }
        public Nullable<int> groupSize { get; set; }
    
        public virtual Room1 Room1 { get; set; }
        public virtual ICollection<Request1> Request1 { get; set; }
    }
}
